[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.ashley:ashley:$ashleyVersion"
  api "com.badlogicgames.box2dlights:box2dlights:$box2dlightsVersion"
  api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.tommyettinger:crux:$cruxVersion"
  api "com.github.tommyettinger:digital:$digitalVersion"
  api "com.github.tommyettinger:funderby:$funderbyVersion"
  api "com.github.tommyettinger:jdkgdxds:$jdkgdxdsVersion"
  api "com.github.tommyettinger:juniper:$juniperVersion"
  api "com.github.tommyettinger:regexodus:$regExodusVersion"
  api "com.github.yellowstonegames.squidsquad:squidcore:$squidSquadVersion"
  api "com.github.yellowstonegames.squidsquad:squidgrid:$squidSquadVersion"
  api "com.github.yellowstonegames.squidsquad:squidplace:$squidSquadVersion"
  api "com.kotcrab.vis:vis-ui:$visUiVersion"
  api "de.golfgl.gdxcontrollerutils:gdx-controllerutils-scene2d:$controllerScene2DVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
